<?php
// +----------------------------------------------------------------------
// | Http.异常接管
// +----------------------------------------------------------------------
// | Copyright (c) 2016 http://www.abc3210.com, All rights reserved.
// +----------------------------------------------------------------------
// | Author: wjf <1937832819@qq.com> 2018/3/23
// +----------------------------------------------------------------------

namespace app\api\exception;

use Exception;
use think\exception\Handle;
use think\Log;

class Http extends Handle
{
    public function render(Exception $e)
    {
        //return parent::render($e); // TODO: Change the autogenerated stub
        //记录错误日志
        Log::record(
            ['message' => $e->getMessage(), 'line' => $e->getLine(), 'file' => $e->getFile()], 'error'
        );
        $data = [
            'status' => 0,
            'error_code' => 10007,
            'msg' => 'unknown error',
        ];
        if (defined('APP_DEBUG') && APP_DEBUG) {
            $data['error']['message'] = $e->getMessage();
            $data['error']['line'] = $e->getLine();
            $data['error']['file'] = $e->getFile();
        }
        return json($data);
    }

}